replicaCount: 1

image:
  repository: ghcr.io/longnt267/nestjs-argocd
  tag: "55eb9b2e4b2e4a3027c754ff8ab99f759baaf22f"
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"